apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hjt9bg37m-nodejs
  janus-idp.io/tekton: hjt9bg37m-nodejs
  backstage.io/kubernetes-id: hjt9bg37m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hjt9bg37m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
